apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: test-fn
spec:
  buildResources:
    limits:
      cpu: 1100m
      memory: 1100Mi
    requests:
      cpu: 700m
      memory: 700Mi
  deps: "{ \n  \"name\": \"hilly-road\",\n  \"version\": \"1.0.0\",\n  \"dependencies\":
    {}\n}"
  maxReplicas: 1
  minReplicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  runtime: nodejs12
  source: "module.exports = { \n  main: function (event, context) {\n    return \"Hello
    World!\";\n  }\n}"

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-func
spec:
  gateways:
  - kyma-gateway.kyma-system.svc.cluster.local
  hosts:
  - test.aj-ser1.cf-kyma-k8.shoot.canary.k8s-hana.ondemand.com
  http:
   - match:
     - uri:
         regex: /.*
     route:
     - destination:
         host: test-fn
         port:
           number: 80
       weight: 100
